#
# General settings
#

debug: false # Send debug messages to console

#
# Currency settings
#

currency:
  name:
    singular: Dollar
    plural: Dollars
  symbol: $
  remove-drops: true # Prevent valuable items from dropping when killing mobs
  count-ender-chest: true # Whether to count ender chest items or not
  format: '#,###.##' # How money will be displayed (1,753.45)
  value: # https://jd.papermc.io/paper/1.21/org/bukkit/Material.html
    COPPER_INGOT: 0.1 # Can contain decimals
    GOLD_INGOT: 1
    GOLD_BLOCK: 9

#
# Auto save settings
#

auto-save:
  enabled: true
  frequency: 900 # Frequency in seconds (900 seconds = every 15 minutes)

update-tracker:
  enabled: true # Check for updates on startup

commands:
  balance:
    enabled: true # This only works on PaperMC and its forks
  pay:
    enabled: true # This only works on PaperMC and its forks