name: banco
authors:
  - myth-MC
  - U8092
version: '${project.version}'
api-version: '1.21'

#loader: ovh.mythmc.gestalt.loader.PaperGestaltLibraryLoader
main: ovh.mythmc.banco.paper.BancoPaperPlugin
folia-supported: true

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    gestalt:
      load: OMIT
      required: false
      join-classpath: true
    social:
      load: OMIT
      required: false
      join-classpath: true
    Essentials:
      load: AFTER
      required: false
    CMI:
      load: AFTER
      required: false
    Towny:
      load: AFTER
      required: false

permissions:
  banco.user:
    default: true
  banco.admin:
    default: op