name: banco
version: '${project.version}'
authors:
  - myth-MC
  - U8092
api-version: '1.20'
main: ovh.mythmc.banco.paper.BancoPaperPlugin
folia-supported: true

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Towny:
      load: AFTER
      required: false
    LiteDelivery:
      load: AFTER
      required: false
    LiteFarm:
      load: AFTER
      required: false
    LiteDungeon:
      load: AFTER
      required: false
    LiteBase:
      load: AFTER
      required: false
    LiteMatter:
      load: AFTER
      required: false
    LiteGuilds:
      load: AFTER
      required: false
    LiteSleep:
      load: AFTER
      required: false

permissions:
  banco.user:
    default: true
  banco.admin:
    default: op